:PROPERTIES:
:ID:       7c550e05-82e1-41d6-a8da-c8171f59f68c
:END:
#+title: corporate tax, some thoughts on
* PITFALL: These are probably out of date.
  I sent them to Oliver and Angelica via Whatsapp.
  Once they build on that, these are garbage.
* Should there be a corporate tax?
** It's redundant.
   The Spanish language is instructive. Corporations are a legal fiction. Ultimately, a corporation's profits go to people. And we already have a personal income tax.
** Progressivity is hard to achieve at the corporate level.
   One could, for instance, impose a progressive marginal tax schedule on corporations. But, since progressivity means taxing the rich more, that approach assumes that companies making more money are giving their money to richer people.
   There's no such link. A giant corporation can take a loss one year; that doesn't mean its money is suddenly going to poorer people. A small corporation -- indeed, any number of small corporations -- can be entirely owned by one rich person. Similarly, a giant corporation can be owned in large part by retirement funds -- i.e., ultimately, by retirees. Those are generally not rich people, regardless of how profitable the giant companies funding their retirements are.
** A corporate tax is inefficient.
*** If there's a corporate tax, there's an industry devoted to minimizing corporate tax bills.
    That's a huge pool of highly educated labor that could be producing something of value but instead is merely shifting value from the state to the private sector.
*** If the average corporate tax rate depends on a corporation's scale, it creates a growth disincentive.
    If small companies pay a lower average tax rate than large companies, that makes small companies want to stay small. But bigger companies are more efficient.
    The effect could be great enough even to cause a company at the margin to want to shrink. Suppose the tax rate is 20% for companies with profits below 1000 million pesos a year, and 30% for a company with profits above. Stated equivalently, big companies can keep 70% of their profits, and small ones can keep 80%.
    Under those conditions, a company that makes 1050 million pesos before taxes will make 0.7 * 1050 = 735 million pesos after taxes. By contrast, a company that makes 950 million pesos before taxes would end up with 950 * 0.8 = 760 million pesos after taxes. A big company could, in December, realize it's about to cross the 1000 million peso threshold and respond by halting operations. That's clearly a terrible use of resources.
** A corporate tax is complex, and thereby less transparent.
   Taxing income twice -- once as corporate income, once as personal dividend income -- can only more complicated than taxing it once would be. And the more complex the process, the harder it is to see what's going on.
* Taxing small enterprises less creates a scale disincentive
  That's bad because scale is efficient. Everything else constant, two small companies are in general less efficient than one bigger company the size of the two small ones.
