:PROPERTIES:
:ID:       d047ae6a-25c0-4ce4-8617-f3c17d29421a
:ROAM_ALIASES: "Encuesta Nacional de Presupuestos de Hogares" ENIG ENPH
:END:
#+title: The ENPH and ENIG surveys of Colombian households, by DANE
* TODO unmerged notes on the [[id:cf5eb548-54b3-48bf-b231-b29d3b627399][enph]]
* TODO [[id:e79b5d00-01ea-44bb-90d9-3772db555875][What are the aggregate income, expenditure variables in the ENPH?]]
* PITFALL: These notes files are redundant
There's an enig.org file, an enph.org file, and this one which pertains to both.
* PITFALL: These notes are stale, from 2018-ish
But they might include some insights into the data due to David Suarez not recorded elsewhere.
* about the variables in it
** [[id:aa3b5635-9936-4c1a-82ce-78ce49bfea40][primary keys (DIR, SEC and ORD) for some DANE data]]
** some GEIH-ENPH variable correspondences
   :PROPERTIES:
   :ID:       84203014-dccc-4ca0-b57a-f83e52b4219b
   :END:
   employment_variables_in_geih_and_enph = {
     # GEIH  : ENPH
     "p1125" : "P6240",
     "p5953" : "P6250",
     "p6260" : "P6260",
     "p8340" : "P6270",
     "p6280" : "P6280",
     "p6310" : "P6310",
     "p6340" : "P6340",
     "p6351" : "P6350",
   }
** [[id:a62dcf88-7357-4b02-b059-b418cd0aa945][Reported labor income is what remains after *some* contributions.]]
* to do
** interpreting frequencies
*** problem: 2.1 or 2?
*** problem: 9 = how infrequent?
**** As a frequency code, 9 usually means "sporadically". I thought that meant "less frequently than every year", assuming that the terms are ordered. But over here it interprets 9 as "Esporádica por semana".
**** links
** Match the covering vocabularies to the COICOP items.
This can be done for all of 2017, and for 2007 goods, but for 2007 services the COICOP data uses an obsolete coding.
** are these more expenditure data sets?
*** sea_enc_gcar_csv
**** NC2_CC_P2
1 » 2. Diario
2 » 2.1. Varias veces por semana
3 » 3. Semanal
4 » 4. Quincenal
5 » 5. Mensual
6 » 6. Bimestral
7 » 7. Trimestral
9 » 9. Esporádica"
*** sea_enc_gcau_csv
**** NC2_CC_P2
1 » 1. Nunca
2 » 2. Diario
3 » 2.1 varias veces por semana
4 » 3. Semanal
5 » 4. Quincenal
6 » 5. Mensual
7 » 6. Bimestral
8 » 7. Trimestral
9 » 9. Esporádica"
ss frequently than every year", assuming that the terms are ordered. But over here it interprets 9 as "Esporádica por semana".
* references
  tax.co/hopefully-obsolete/enig-enph,email,david-suarez,2018-02-23.md
