:PROPERTIES:
:ID:       7971c41c-a733-4e13-8207-8664b75b39b7
:END:
#+title: graph changes in tax burden by decile in tax.co.web
* How to draw.
** draw arrows, red for up, green for down
   :PROPERTIES:
   :ID:       bf27d9d3-3dc0-418f-8a32-322d65c0dc93
   :END:
   See
     arrows_on_bars()
   in
     python/draw/examples.py
** to draw paired bar charts, like we did in the `cities` repo
   ~/of/_old/cities/Code/draw/chart/pairs.py
* TODO Create the (new?) variable "tax".
** where to find them
** some variables
   :PROPERTIES:
   :ID:       5ddcf6f3-75c6-4d0a-abea-00e612953ebb
   :END:
*** VAT paid
*** tax, income = the sum of
    python/regime/r2019.py

    "tax, income, most"
    "tax, income, dividend"
    "tax, income, ganancia ocasional"
    "tax, income, gmf"
*** BLOCKED (asking Luis) about ss taxes
**** raw
     cesantias + primas             # PITFALL: nominally from the employer
     tax, ss, cajas de compensacion # PITFALL: nominally from the employer
     tax, ss, parafiscales	    # PITFALL: nominally from the employer
     tax, ss, solidaridad
     tax, ss, salud
     tax, ss, salud, employer
     tax, ss, pension
     tax, ss, pension, employer
**** a partial sum
     ppl["tax, ss, total employee contribs"] = (
       ppl["tax, ss, pension"] +
       ppl["tax, ss, salud"] +
       ppl["tax, ss, solidaridad"] )
*** purchase_sums["value, tax, purchaselike non-VAT"] = (
      purchase_sums["value, tax, predial"] +
      purchase_sums["value, tax, purchaselike non-predial non-VAT"] )
* TODO Make a baseline every time.
  :PROPERTIES:
  :ID:       b8f2e47c-a378-439b-8836-769065fb41be
  :END:
** Bear in mind that [[id:106ca7be-c9de-42c6-89aa-db93c5202304][this]] means the baseline is approximate.
** Don't modify the Makefile, but create a new user.
   Call the user "baseline" (no ampersand needed).
   Check user/baseline/ into git.
   In run-makefile.py, first run on baseline,
   then on the current user.
** Just run it once, for the full sample.
* TODO Draw something that compares to the baseline.
** Compare the full-sample baseline results to the current user's.
   Do that even if the current user is using another subsample.
   It can only help.
