:PROPERTIES:
:ID:       7971c41c-a733-4e13-8207-8664b75b39b7
:END:
#+title: graph changes in tax burden by decile in tax.co.web
* How to draw.
** draw arrows, red for up, green for down
   :PROPERTIES:
   :ID:       bf27d9d3-3dc0-418f-8a32-322d65c0dc93
   :END:
   See
     arrows_on_bars()
   in
     python/draw/examples.py
** to draw paired bar charts, like we did in the `cities` repo
   ~/of/_old/cities/Code/draw/chart/pairs.py
* TODO Include every tax in the (new?) variable "tax".
  The horizontal axis will be income deciles or percentiles.
  The vertical one needs to be the sum of all taxes.
    The income column is just "income".
    VAT paid
      is the VAT column
    tax, income
      is the major one
    All of these might or might not be part of "tax, income"
      tax, income, gmf
      cesantias
      tax, ss, cajas de compensacion
      tax, ss, parafiscales
      tax, ss, solidaridad
      tax, ss, salud, employer
      tax, ss, salud
    Some that we're ignoring?
      tax, predial
      whatever else is similar to that
* TODO Make a baseline every time.
  :PROPERTIES:
  :ID:       b8f2e47c-a378-439b-8836-769065fb41be
  :END:
** Bear in mind that [[id:106ca7be-c9de-42c6-89aa-db93c5202304][this]] means the baseline is approximate.
** Don't modify the makefile, but create a new user.
   Call the user "baseline" (no ampersand needed).
   Check user/baseline/ into git.
   In run-makefile.py, first run on baseline,
   then on the current user.
** Just run it once, for the full sample.
* TODO Draw something that compares to the baseline.
** Compare the full-sample baseline results to the current user's.
   Do that even if the current user is using another subsample.
   It can only help.
